sonar.projectKey=guilhermelinosp_hellnet-lib-cache
sonar.organization=guilhermelinosp
sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
