name: test-quality-only

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    name: quality
    uses: guilhermelinosp/templates/.github/workflows/lib-quality.yml@e7d093b460c1e25f16121d509eefcbb597612c95 # main
    with:
      go-version-file: go.mod
