name: test-release-only

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: release
    uses: guilhermelinosp/templates/.github/workflows/release.yml@da82921830fafa7349cda3faef3310a3a4d86dda # main
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
