name: test-quality-only

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    name: quality
    uses: guilhermelinosp/templates/.github/workflows/lib-quality.yml@da82921830fafa7349cda3faef3310a3a4d86dda # main
    with:
      go-version-file: go.mod
